service: tudor-serverless
# app and org for use with dashboard.serverless.com
app: tudor
org: pfoucht

provider:
  name: aws
  runtime: nodejs12.x
  role: arn:aws:iam::358614248599:role/TudorServerlessRole
  stage: dev
  environment:
    MEETINGS_TABLE: Meetings--${self:service}-${self:provider.stage}

functions:
  join:
    handler: handlers/chime/join.join
    events:
      - http:
          path: meeting/join
          method: post
          cors: true
  # leave:
  #   handler: handlers/chime/join.leave
  #   events:
  #     - http:
  #         path: meeting/leave
  #         method: post
  #         cors: true

# you can add CloudFormation resource templates here
resources:
  Resources:
    meetingsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.MEETINGS_TABLE}
        AttributeDefinitions:
          - AttributeName: 'Title'
            AttributeType: 'S'
          - AttributeName: 'Passcode'
            AttributeType: 'S'
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: 'Title'
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: 'Passcode'
            KeySchema:
              - AttributeName: 'Passcode'
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        TimeToLiveSpecification:
          AttributeName: 'TTL'
          Enabled: true

Outputs:
  MeetingsTableArn:
    Description: The ARN for the Meetings's Table
    Value:
      'Fn::GetAtt': [meetingsTable, Arn]
    Export:
      Name: ${self:provider.environment.MEETINGS_TABLE}
